package mx.softixx.cis.common.core.datetime;

public enum MonthName {
	ENERO, JANUARY, ENE, JAN, FEBRERO, FEBRUARY, FEB, MARZO, MARCH, MAR, ABRIL, APRIL, ABR, APR, MAYO, MAY, JUNIO,
	JUNE, JUN, JULIO, JULY, JUL, AGOSTO, AUGUST, AUG, SEPTIEMBRE, SEPTEMBER, SEP, OCTUBRE, OCTOBER, OCT, NOVIEMBRE,
	NOVEMBER, NOV, DICIEMBRE, DECEMBER, DIC, DEC
}